### ISSUE TITLE
CRON_STRINGS in examples may not be correct.

### ISSUE THREAD

**Issue by chenll7** [xordiv/docker-alpine-cron#4]
I want to run rsync by cron.
But cron task exited with 127 while using `ENV CRON_STRINGS="* * * * * root /usr/bin/rsync -r -a --delete /src/ /dst"`. And   `ENV CRON_STRINGS="* * * * * /usr/bin/rsync -r -a --delete /src/ /dst"` worked.

**Comment by elitan** [comment]
related: https://serverfault.com/questions/277706/cron-fails-with-exit-status-127

**Comment by elitan** [comment]
I went on to use [tigpt/cronjobs](https://github.com/tigpt/cronjobs) instead.

**Comment by xordiv** [comment]
Fixed, thank you.
